shim-version: v0.4.2@sha256:d65f769e37bbe86ffaeef42120c29c4b9de33415fcd7588a9ef7a64f609aa2a3
cvm-version: 0.6.10
cpus: 128
memory: 1966080

containers:
  - name: ml-inference
    image: "us-central1-docker.pkg.dev/workshop-labs-pbc/pollux-docker/ml-inference-multigpu@sha256:c8d0e79894c2a7c13712256c7e0ca728118a70c916455ed107bf895f73509ef8"
    entrypoint:
      - python
    command:
      - -m
      - scripts.inference_server
      - hf-kimi-k2-thinking
    runtime: nvidia
    gpus: all
    ipc: host
    env:
      - GOOGLE_APPLICATION_CREDENTIALS: /key.json
      - POLLUX_LN_GCS_BUCKET: gs://pollux-enc-prod
      - KEY_MODE: real_keys
    volumes:
      - /mnt/ramdisk/gcloud_key.json:/key.json:ro
      - /mnt/ramdisk/data:/data
    secrets:
      - gcloud-key
      - HF_TOKEN
      - INTERNAL_SERVICE_SECRET

shim:
  listen-port: 443
  upstream-port: 8000
  publish-attestation: true
  tls-challenge: dns
  paths:
    - /ping
    - /v1/chat/completions
    - /v1/loaded_model
    - /v1/metrics/vllm/full
    - /v1/metrics/short
    - /v1/downloaded_models
    - /v1/downloaded_models_reset
    - /v1/user/*
